version: "3.9"
services:
  nginx:
    build: ./nginx/
    ports:
      - 80:80

    volumes:
        - ./php_code/:/var/www/html/

  php:
    build: ./php_code/
    expose:
      - 9000
    volumes:
      - ./php_code/:/var/www/html/

    depends_on:
      - db

  db:
      image: mariadb
      volumes:
        -   mysql-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 1
        MYSQL_DATABASE: percobaan
  
volumes:
    mysql-data:
